# @keepStreaming
WS wss://0lopc7lwp8.execute-api.us-east-1.amazonaws.com/production

{{@streaming
async function writeStream(){
    await sleep(1000);
    let message = 'hello'
    websocketClient.send('message');
    await sleep(1000);
}
exports.waitPromise = writeStream();
}}

###
WS 1006
###
GET https://slack.com/api/users.lookupByEmail?email=jjansena@amazon.com
Content-Type: application/json; charset=utf-8
Authorization: Bearer xoxb-4336805381572-4340538201219-V3LPnnVMaIvs2RuzCb2nuzns



HTTP/1.1 200  - OK
date: Wed, 04 Jan 2023 18:19:44 GMT
server: Apache
x-powered-by: HHVM/4.153.1
access-control-allow-origin: *
referrer-policy: no-referrer
x-slack-backend: r
x-slack-unique-id: Y7XDQKxhnuSGxwreD_nxYQAAAAU
strict-transport-security: max-age=31536000; includeSubDomains; preload
access-control-allow-headers: slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags
access-control-expose-headers: x-slack-req-id, retry-after
x-oauth-scopes: incoming-webhook,channels:manage,groups:write,im:write,mpim:write,commands,chat:write,chat:write.customize,chat:write.public,users:read.email,users:read,users.profile:read,channels:read,conversations.connect:manage
x-accepted-oauth-scopes: users:read.email
expires: Mon, 26 Jul 1997 05:00:00 GMT
cache-control: private, no-cache, no-store, must-revalidate
pragma: no-cache
x-xss-protection: 0
x-content-type-options: nosniff
x-slack-req-id: cbe00d881e87788b50298c58726916a9
vary: Accept-Encoding
content-encoding: gzip
content-length: 689
content-type: application/json; charset=utf-8
x-envoy-upstream-service-time: 107
x-backend: main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow
x-server: slack-www-hhvm-main-iad-aeog
x-slack-shared-secret-outcome: no-match
via: envoy-www-iad-wvan, envoy-edge-pdx-6pjl
x-edge-backend: envoy-www
x-slack-edge-shared-secret-outcome: no-match
connection: close